from google.streetview.publish_v1.proto.resources_pb2 import Photo, UploadRef
from google.oauth2.credentials import Credentials

class StreetViewPublishServiceClient:
    def __init__(self, credentials: Credentials | None = None): ...
    def start_upload(self) -> UploadRef: ...
    def create_photo(self, photo: Photo) -> Photo: ...
    def delete_photo(self, photo_id: str) -> None: ...
